### ISSUE TITLE
Support for lists

### ISSUE THREAD

**Issue by grefel** [barooney/wp-id-exchange#44]
Ordered and unordered lists produce non well formed XML-Output. 

`<p><ol></p><p>     <li>Ein Listenpunkt</li></p><p>     <li>Der zweite Listenpunkt£</li></p><p></ol></p></pre>`

`<ol>` is accidently wrapped with `<p>`

**Comment by barooney** [comment]
Good catch there!

Version 1.0.1 should have fixed it. My test with the following input succeeded:

```
<ol>
    <li>Ein Listenpunkt</li>
    <li>Der zweite Listenpunkt</li>
</ol>
```
